version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t imkulikov/php7:${CIRCLE_TAG} .
      - run:
         command: docker run -it imkulikov/php7:${CIRCLE_TAG} sh -c "php -v && php -m"
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push imkulikov/php7:${CIRCLE_TAG}
workflows:
  version: 2
  build:
    jobs:
      - build
