version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t imkulikov/php7:$(git tag --contains) .
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push imkulikov/php7:$(git tag --contains)
workflows:
  version: 2
  build:
    jobs:
      - build
